const AppActionsConstants = {
    UPDATE_TAG: 'UPDATE_TAG',
    LOAD_TAGS: 'LOAD_TAGS',
    LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    UPDATE_LOGIN: 'UPDATE_LOGIN'
};

export { AppActionsConstants}
