const AppActionsConstants = {
    UPDATE_TAG: 'UPDATE_TAG',
    LOAD_TAGS: 'LOAD_TAGS',
    LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    UPDATE_LOGIN: 'UPDATE_LOGIN',
    UPDATE_LOGGED_NAME: 'UPDATE_LOGGED_NAME',
    UPDATE_LOGGED_LOCATION: 'UPDATE_LOGGED_LOCATION',
    UPDATE_LOGGED_REVIEWS: 'UPDATE_LOGGED_REVIEWS'
};

export { AppActionsConstants}
