const ProfilesActionsConstants = {
    SEARCH_REVIEWS: 'SEARCH_REVIEWS',
    SEARCH_REVIEWS_SUCCESS: 'SEARCH_REVIEWS_SUCCESS',
    SEARCH_REVIEWS_FAIL: "SEARCH_REVIEWS_FAIL",
    FETCH_ALL_PROFILES: "FETCH_ALL_PROFILES",
    FETCH_ALL_PROFILES_SUCCESS: "FETCH_ALL_PROFILES_SUCCESS",
    SORT_KEY_CHANGED: "SORT_KEY_CHANGED",
    LAYOUT_CHANGED: "LAYOUT_CHANGED",
    FETCH_USERS_REVIEWS: 'FETCH_USERS_REVIEWS',
    FETCH_USERS_REVIEWS_SUCCESS: 'FETCH_USERS_REVIEWS_SUCCESS',
    FETCH_USERS_REVIEWS_FAIL: 'FETCH_USERS_REVIEWS_FAIL'

}

export {ProfilesActionsConstants}