const SelfProfileActionsConstants = {
   UPDATE_STATE: 'UPDATE_STATE',
   UPDATE_STATE_SUCCESS: 'UPDATE_STATE_SUCCESS',
   UPDATE_STATE_FAIL: 'UPDATE_STATE_FAIL',
   ADD_REVIEW: 'ADD_REVIEW',
   SAVE_REVIEW: 'SAVE_REVIEW',
   SAVE_REVIEW_SUCCESS: 'SAVE_REVIEW_SUCCESS',
   SAVE_REVIEW_FAIL: 'SAVE_REVIEW_FAIL'
}

export { SelfProfileActionsConstants }