const SelfProfileActionsConstants = {
    FETCH_REVIEWS: 'FETCH_REVIEWS',
    UPDATE_REVIEWS_SUCCESS: 'UPDATE_REVIEWS_SUCCESS',
    FETCH_REVIEWS_SUCCESS: 'FETCH_REVIEWS_SUCCESS',
    ADD_REVIEW: 'ADD_REVIEW',
    UPDATE_REVIEWS: 'UPDATE_REVIEWS',
    SAVE_REVIEW: 'SAVE_REVIEW',
    SAVE_REVIEW_SUCCESS: 'SAVE_REVIEW_SUCCESS',
    SAVE_REVIEW_FAIL: 'SAVE_REVIEW_FAIL',
    EDIT_REVIEW: 'EDIT_REVIEW',
    EDIT_REVIEW_SUCCESS: 'EDIT_REVIEW_SUCCESS',
    EDIT_REVIEW_FAIL: 'EDIT_REVIEW_FAIL',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
    DELETE_REVIEW_FAIL: 'DELETE_REVIEW_FAIL'
}

export { SelfProfileActionsConstants }