const RegisterActionsConstants = {
    LOAD_CITIES: 'LOAD_CITIES',
    UPDATE_NAME: 'UPDATE_NAME',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    SUGGEST_LOCATIONS: 'SUGGEST_LOCATIONS',
    CLICK: 'CLICK',
    UPDATE_NAME_SUCCESS: 'UPDATE_NAME_SUCCESS',
    UPDATE_NAME_FAIL: 'UPDATE_NAME_FAIL',
    CLICK_SUCCESS: 'CLICK_SUCCESS',
    CLICK_FAIL: 'CLICK_FAIL'
}

export {RegisterActionsConstants}