const RestaurantsActionsConstants = {
    SEARCH_REVIEWS: 'SEARCH_REVIEWS',
    SEARCH_REVIEWS_SUCCESS: 'SEARCH_REVIEWS_SUCCESS',
    SEARCH_REVIEWS_FAIL: "SEARCH_REVIEWS_FAIL",
    FETCH_ALL_RESTAURANTS: "FETCH_ALL_RESTAURANTS",
    FETCH_ALL_RESTAURANTS_SUCCESS: "FETCH_ALL_RESTAURANTS_SUCCESS",
    SORT_KEY_CHANGED: "SORT_KEY_CHANGED",
    LAYOUT_CHANGED: "LAYOUT_CHANGED",
    FETCH_RESTAURANT_REVIEWS: 'FETCH_RESTAURANT_REVIEWS',
    FETCH_RESTAURANT_REVIEWS_SUCCESS: 'FETCH_RESTAURANT_REVIEWS_SUCCESS',
    FETCH_RESTAURANT_REVIEWS_FAIL: 'FETCH_RESTAURANT_REVIEWS_FAIL'

}

export { RestaurantsActionsConstants }