const LoginActionsConstants = {
    UPDATE_LOGIN_NAME: 'UPDATE_LOGIN_NAME',
    UPDATE_LOGIN_PASSWORD: 'UPDATE_LOGIN_PASSWORD',
    LOGIN_BUTTON: 'LOGIN_BUTTON',
    LOGIN_BUTTON_SUCCESS: 'LOGIN_BUTTON_SUCCESS',
    LOGIN_BUTTON_FAIL: 'LOGIN_BUTTON_FAIL'
};

export { LoginActionsConstants }