const SelfPropertiesActionsConstants = {
    UPDATE_EDITED_NAME: 'UPDATE_EDITED_NAME',
    UPDATE_EDITED_LOCATION: 'UPDATE_EDITED_LOCATION',
    UPDATE_NEW_NAME:'UPDATE_NEW_NAME',
    UPDATE_NEW_NAME_SUCCESS: 'UPDATE_NAME_SUCCESS',
    UPDATE_NEW_NAME_FAIL: 'UPDATE_NEW_NAME_FAIL',
    UPDATE_NEW_LOCATION:'UPDATE_NEW_LOCATION',
    UPDATE_NEW_LOCATION_SUCCESS: 'UPDATE_NEW_LOCATION_SUCCESS',
    UPDATE_NEW_LOCATION_FAIL: 'UPDATE_NEW_LOCATION_FAIL'
}

export { SelfPropertiesActionsConstants }