const SelfPropertiesActionsConstants = {
    UPDATE_EDITED_NAME: 'UPDATE_EDITED_NAME',
    UPDATE_EDITED_LOCATION: 'UPDATE_EDITED_LOCATION',
    UPDATE_NAME:'UPDATE_NAME',
    UPDATE_NAME_SUCCESS: 'UPDATE_NAME_SUCCESS',
    UPDATE_NAME_FAIL: 'UPDATE_NAME_FAIL',
    UPDATE_LOCATION:'UPDATE_LOCATION',
    UPDATE_LOCATION_SUCCESS: 'UPDATE_LOCATION_SUCCESS',
    UPDATE_LOCATION_FAIL: 'UPDATE_LOCATION_FAIL'
}

export { SelfPropertiesActionsConstants }