const ReviewActionsConstants = {
    EDIT_CLICK: 'EDIT_CLICK',
    SAVE_STARS: 'SAVE_STARS',
    CHANGE_STARS: 'CHANGE_STARS',
    SAVE_STARSS_SUCCESS: 'SAVE_STARS_SUCCESS',
    SAVE_STARS_FAIL: 'SAVE_STARS_FAIL',
    UPDATE_DELETED: 'UPDATE_DELETED'
}

export { ReviewActionsConstants }