const ReviewActionsConstants = {
    EDIT_CLICK: 'EDIT_CLICK',
    SAVE_STARS: 'SAVE_STARS',
    SAVE_STARS_SUCCESS: 'SAVE_STARS_SUCCESS',
    SAVE_STARS_FAIL: 'SAVE_STARS_FAIL',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
    DELETE_REVIEW_FAIL: 'DELETE_REVIEW_FAIL'
}

export { ReviewActionsConstants }